export const CATEGORIES = [
  { name: 'All', imageUrls: ['https://picsum.photos/seed/people/48/48', 'https://picsum.photos/seed/landscape/48/48'] },
  { name: 'Nature', imageUrl: 'https://picsum.photos/seed/nature/48/48' },
  { name: 'Wallpapers', imageUrl: 'https://picsum.photos/seed/wallpaper/48/48' },
  { name: 'Travel', imageUrl: 'https://picsum.photos/seed/travel/48/48' },
  { name: 'Architecture', imageUrl: 'https://picsum.photos/seed/architecture/48/48' },
  { name: 'Landmarks', imageUrl: 'https://picsum.photos/seed/landmark/48/48' },
  { name: 'Cityscapes', imageUrl: 'https://picsum.photos/seed/cityscape/48/48' },
  { name: 'Street Photography', imageUrl: 'https://picsum.photos/seed/street/48/48' },
  { name: 'Wildlife', imageUrl: 'https://picsum.photos/seed/wildlife/48/48' },
  { name: 'Underwater', imageUrl: 'https://picsum.photos/seed/underwater/48/48' },
  { name: 'Animals', imageUrl: 'https://picsum.photos/seed/animal/48/48' },
  { name: 'Food', imageUrl: 'https://picsum.photos/seed/food/48/48' },
  { name: 'Fashion', imageUrl: 'https://picsum.photos/seed/fashion/48/48' },
  { name: 'People', imageUrl: 'https://picsum.photos/seed/people/48/48' },
  { name: 'Technology', imageUrl: 'https://picsum.photos/seed/technology/48/48' },
  { name: 'Business', imageUrl: 'https://picsum.photos/seed/business/48/48' },
  { name: 'Sports', imageUrl: 'https://picsum.photos/seed/sports/48/48' },
  { name: 'Health & Wellness', imageUrl: 'https://picsum.photos/seed/health/48/48' },
  { name: 'Music', imageUrl: 'https://picsum.photos/seed/music/48/48' },
  { name: 'Science', imageUrl: 'https://picsum.photos/seed/science/48/48' },
  { name: 'Education', imageUrl: 'https://picsum.photos/seed/education/48/48' },
  { name: 'History', imageUrl: 'https://picsum.photos/seed/history/48/48' },
  { name: 'Textures & Patterns', imageUrl: 'https://picsum.photos/seed/texture/48/48' },
  { name: 'Abstract', imageUrl: 'https://picsum.photos/seed/abstract/48/48' },
  { name: 'Art', imageUrl: 'https://picsum.photos/seed/art/48/48' },
  { name: 'Minimalism', imageUrl: 'https://picsum.photos/seed/minimalism/48/48' },
  { name: 'Interiors', imageUrl: 'https://picsum.photos/seed/interior/48/48' },
  { name: 'Cars', imageUrl: 'https://picsum.photos/seed/car/48/48' },
  { name: 'Flowers', imageUrl: 'https://picsum.photos/seed/flower/48/48' },
  { name: 'Holidays', imageUrl: 'https://picsum.photos/seed/holiday/48/48' },
  { name: 'Portraits', imageUrl: 'https://picsum.photos/seed/portrait/48/48' },
  { name: 'Events', imageUrl: 'https://picsum.photos/seed/event/48/48' },
  { name: 'Film', imageUrl: 'https://picsum.photos/seed/film/48/48' },
  { name: 'Black and White', imageUrl: 'https://picsum.photos/seed/bnw/48/48' },
  { name: 'Drones', imageUrl: 'https://picsum.photos/seed/drone/48/48' },
  { name: 'Astrophotography', imageUrl: 'https://picsum.photos/seed/astro/48/48' },
  { name: 'Still Life', imageUrl: 'https://picsum.photos/seed/stilllife/48/48' },
  { name: 'Vintage', imageUrl: 'https://picsum.photos/seed/vintage/48/48' },
];

export const IMAGES_PER_PAGE = 24;
export const TOTAL_PAGES = 834;